# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from backend.models.base_model_ import Model
from backend import util


class MAMSettings(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, default: str=None, always: List[str]=None, never: List[str]=None, created_at: datetime=None):  # noqa: E501
        """MAMSettings - a model defined in Swagger

        :param default: The default of this MAMSettings.  # noqa: E501
        :type default: str
        :param always: The always of this MAMSettings.  # noqa: E501
        :type always: List[str]
        :param never: The never of this MAMSettings.  # noqa: E501
        :type never: List[str]
        :param created_at: The created_at of this MAMSettings.  # noqa: E501
        :type created_at: datetime
        """
        self.swagger_types = {
            'default': str,
            'always': List[str],
            'never': List[str],
            'created_at': datetime
        }

        self.attribute_map = {
            'default': 'default',
            'always': 'always',
            'never': 'never',
            'created_at': 'created_at'
        }
        self._default = default
        self._always = always
        self._never = never
        self._created_at = created_at

    @classmethod
    def from_dict(cls, dikt) -> 'MAMSettings':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MAMSettings of this MAMSettings.  # noqa: E501
        :rtype: MAMSettings
        """
        return util.deserialize_model(dikt, cls)

    @property
    def default(self) -> str:
        """Gets the default of this MAMSettings.


        :return: The default of this MAMSettings.
        :rtype: str
        """
        return self._default

    @default.setter
    def default(self, default: str):
        """Sets the default of this MAMSettings.


        :param default: The default of this MAMSettings.
        :type default: str
        """

        self._default = default

    @property
    def always(self) -> List[str]:
        """Gets the always of this MAMSettings.


        :return: The always of this MAMSettings.
        :rtype: List[str]
        """
        return self._always

    @always.setter
    def always(self, always: List[str]):
        """Sets the always of this MAMSettings.


        :param always: The always of this MAMSettings.
        :type always: List[str]
        """

        self._always = always

    @property
    def never(self) -> List[str]:
        """Gets the never of this MAMSettings.


        :return: The never of this MAMSettings.
        :rtype: List[str]
        """
        return self._never

    @never.setter
    def never(self, never: List[str]):
        """Sets the never of this MAMSettings.


        :param never: The never of this MAMSettings.
        :type never: List[str]
        """

        self._never = never

    @property
    def created_at(self) -> datetime:
        """Gets the created_at of this MAMSettings.


        :return: The created_at of this MAMSettings.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """Sets the created_at of this MAMSettings.


        :param created_at: The created_at of this MAMSettings.
        :type created_at: datetime
        """

        self._created_at = created_at
