# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from backend.models.base_model_ import Model
from backend.models.error_result import ErrorResult  # noqa: F401,E501
from backend.models.mam_message import MAMMessage  # noqa: F401,E501
from backend.models.mam_message_list import MAMMessageList  # noqa: F401,E501
from backend import util


class MAMMessageListResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, messages: List[MAMMessage]=None, result: str=None, error: str=None):  # noqa: E501
        """MAMMessageListResponse - a model defined in Swagger

        :param messages: The messages of this MAMMessageListResponse.  # noqa: E501
        :type messages: List[MAMMessage]
        :param result: The result of this MAMMessageListResponse.  # noqa: E501
        :type result: str
        :param error: The error of this MAMMessageListResponse.  # noqa: E501
        :type error: str
        """
        self.swagger_types = {
            'messages': List[MAMMessage],
            'result': str,
            'error': str
        }

        self.attribute_map = {
            'messages': 'messages',
            'result': 'result',
            'error': 'error'
        }
        self._messages = messages
        self._result = result
        self._error = error

    @classmethod
    def from_dict(cls, dikt) -> 'MAMMessageListResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MAMMessageListResponse of this MAMMessageListResponse.  # noqa: E501
        :rtype: MAMMessageListResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def messages(self) -> List[MAMMessage]:
        """Gets the messages of this MAMMessageListResponse.


        :return: The messages of this MAMMessageListResponse.
        :rtype: List[MAMMessage]
        """
        return self._messages

    @messages.setter
    def messages(self, messages: List[MAMMessage]):
        """Sets the messages of this MAMMessageListResponse.


        :param messages: The messages of this MAMMessageListResponse.
        :type messages: List[MAMMessage]
        """

        self._messages = messages

    @property
    def result(self) -> str:
        """Gets the result of this MAMMessageListResponse.


        :return: The result of this MAMMessageListResponse.
        :rtype: str
        """
        return self._result

    @result.setter
    def result(self, result: str):
        """Sets the result of this MAMMessageListResponse.


        :param result: The result of this MAMMessageListResponse.
        :type result: str
        """

        self._result = result

    @property
    def error(self) -> str:
        """Gets the error of this MAMMessageListResponse.


        :return: The error of this MAMMessageListResponse.
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error: str):
        """Sets the error of this MAMMessageListResponse.


        :param error: The error of this MAMMessageListResponse.
        :type error: str
        """

        self._error = error
