# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from backend.models.base_model_ import Model
from backend import util


class OneOfRegister(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self):  # noqa: E501
        """OneOfRegister - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'OneOfRegister':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OneOfRegister of this OneOfRegister.  # noqa: E501
        :rtype: OneOfRegister
        """
        return util.deserialize_model(dikt, cls)
