# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from backend.models.base_model_ import Model
from backend import util


class RegisterPassword(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, login: str=None, password: str=None, hash: str=None):  # noqa: E501
        """RegisterPassword - a model defined in Swagger

        :param login: The login of this RegisterPassword.  # noqa: E501
        :type login: str
        :param password: The password of this RegisterPassword.  # noqa: E501
        :type password: str
        :param hash: The hash of this RegisterPassword.  # noqa: E501
        :type hash: str
        """
        self.swagger_types = {
            'login': str,
            'password': str,
            'hash': str
        }

        self.attribute_map = {
            'login': 'login',
            'password': 'password',
            'hash': 'hash'
        }
        self._login = login
        self._password = password
        self._hash = hash

    @classmethod
    def from_dict(cls, dikt) -> 'RegisterPassword':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RegisterPassword of this RegisterPassword.  # noqa: E501
        :rtype: RegisterPassword
        """
        return util.deserialize_model(dikt, cls)

    @property
    def login(self) -> str:
        """Gets the login of this RegisterPassword.


        :return: The login of this RegisterPassword.
        :rtype: str
        """
        return self._login

    @login.setter
    def login(self, login: str):
        """Sets the login of this RegisterPassword.


        :param login: The login of this RegisterPassword.
        :type login: str
        """
        if login is None:
            raise ValueError("Invalid value for `login`, must not be `None`")  # noqa: E501

        self._login = login

    @property
    def password(self) -> str:
        """Gets the password of this RegisterPassword.


        :return: The password of this RegisterPassword.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this RegisterPassword.


        :param password: The password of this RegisterPassword.
        :type password: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    @property
    def hash(self) -> str:
        """Gets the hash of this RegisterPassword.


        :return: The hash of this RegisterPassword.
        :rtype: str
        """
        return self._hash

    @hash.setter
    def hash(self, hash: str):
        """Sets the hash of this RegisterPassword.


        :param hash: The hash of this RegisterPassword.
        :type hash: str
        """
        if hash is None:
            raise ValueError("Invalid value for `hash`, must not be `None`")  # noqa: E501

        self._hash = hash
