# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from backend.models.base_model_ import Model
from backend import util


class Roster(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, jid: str=None, name: str=None):  # noqa: E501
        """Roster - a model defined in Swagger

        :param jid: The jid of this Roster.  # noqa: E501
        :type jid: str
        :param name: The name of this Roster.  # noqa: E501
        :type name: str
        """
        self.swagger_types = {
            'jid': str,
            'name': str
        }

        self.attribute_map = {
            'jid': 'jid',
            'name': 'name'
        }
        self._jid = jid
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'Roster':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Roster of this Roster.  # noqa: E501
        :rtype: Roster
        """
        return util.deserialize_model(dikt, cls)

    @property
    def jid(self) -> str:
        """Gets the jid of this Roster.


        :return: The jid of this Roster.
        :rtype: str
        """
        return self._jid

    @jid.setter
    def jid(self, jid: str):
        """Sets the jid of this Roster.


        :param jid: The jid of this Roster.
        :type jid: str
        """

        self._jid = jid

    @property
    def name(self) -> str:
        """Gets the name of this Roster.


        :return: The name of this Roster.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Roster.


        :param name: The name of this Roster.
        :type name: str
        """

        self._name = name
