# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from backend.models.base_model_ import Model
from backend.models.roster import Roster  # noqa: F401,E501
from backend import util


class RosterList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, roster: List[Roster]=None):  # noqa: E501
        """RosterList - a model defined in Swagger

        :param roster: The roster of this RosterList.  # noqa: E501
        :type roster: List[Roster]
        """
        self.swagger_types = {
            'roster': List[Roster]
        }

        self.attribute_map = {
            'roster': 'roster'
        }
        self._roster = roster

    @classmethod
    def from_dict(cls, dikt) -> 'RosterList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RosterList of this RosterList.  # noqa: E501
        :rtype: RosterList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def roster(self) -> List[Roster]:
        """Gets the roster of this RosterList.


        :return: The roster of this RosterList.
        :rtype: List[Roster]
        """
        return self._roster

    @roster.setter
    def roster(self, roster: List[Roster]):
        """Sets the roster of this RosterList.


        :param roster: The roster of this RosterList.
        :type roster: List[Roster]
        """

        self._roster = roster
