# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from backend.models.base_model_ import Model
from backend import util


class VCard(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, jid: str=None, vcard: object=None):  # noqa: E501
        """VCard - a model defined in Swagger

        :param jid: The jid of this VCard.  # noqa: E501
        :type jid: str
        :param vcard: The vcard of this VCard.  # noqa: E501
        :type vcard: object
        """
        self.swagger_types = {
            'jid': str,
            'vcard': object
        }

        self.attribute_map = {
            'jid': 'jid',
            'vcard': 'vcard'
        }
        self._jid = jid
        self._vcard = vcard

    @classmethod
    def from_dict(cls, dikt) -> 'VCard':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VCard of this VCard.  # noqa: E501
        :rtype: VCard
        """
        return util.deserialize_model(dikt, cls)

    @property
    def jid(self) -> str:
        """Gets the jid of this VCard.


        :return: The jid of this VCard.
        :rtype: str
        """
        return self._jid

    @jid.setter
    def jid(self, jid: str):
        """Sets the jid of this VCard.


        :param jid: The jid of this VCard.
        :type jid: str
        """

        self._jid = jid

    @property
    def vcard(self) -> object:
        """Gets the vcard of this VCard.


        :return: The vcard of this VCard.
        :rtype: object
        """
        return self._vcard

    @vcard.setter
    def vcard(self, vcard: object):
        """Sets the vcard of this VCard.


        :param vcard: The vcard of this VCard.
        :type vcard: object
        """

        self._vcard = vcard
