# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from backend.models.base_model_ import Model
from backend.models.error_result import ErrorResult  # noqa: F401,E501
from backend.models.v_card import VCard  # noqa: F401,E501
from backend import util


class VCardResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, jid: str=None, vcard: object=None, result: str=None, error: str=None):  # noqa: E501
        """VCardResponse - a model defined in Swagger

        :param jid: The jid of this VCardResponse.  # noqa: E501
        :type jid: str
        :param vcard: The vcard of this VCardResponse.  # noqa: E501
        :type vcard: object
        :param result: The result of this VCardResponse.  # noqa: E501
        :type result: str
        :param error: The error of this VCardResponse.  # noqa: E501
        :type error: str
        """
        self.swagger_types = {
            'jid': str,
            'vcard': object,
            'result': str,
            'error': str
        }

        self.attribute_map = {
            'jid': 'jid',
            'vcard': 'vcard',
            'result': 'result',
            'error': 'error'
        }
        self._jid = jid
        self._vcard = vcard
        self._result = result
        self._error = error

    @classmethod
    def from_dict(cls, dikt) -> 'VCardResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VCardResponse of this VCardResponse.  # noqa: E501
        :rtype: VCardResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def jid(self) -> str:
        """Gets the jid of this VCardResponse.


        :return: The jid of this VCardResponse.
        :rtype: str
        """
        return self._jid

    @jid.setter
    def jid(self, jid: str):
        """Sets the jid of this VCardResponse.


        :param jid: The jid of this VCardResponse.
        :type jid: str
        """

        self._jid = jid

    @property
    def vcard(self) -> object:
        """Gets the vcard of this VCardResponse.


        :return: The vcard of this VCardResponse.
        :rtype: object
        """
        return self._vcard

    @vcard.setter
    def vcard(self, vcard: object):
        """Sets the vcard of this VCardResponse.


        :param vcard: The vcard of this VCardResponse.
        :type vcard: object
        """

        self._vcard = vcard

    @property
    def result(self) -> str:
        """Gets the result of this VCardResponse.


        :return: The result of this VCardResponse.
        :rtype: str
        """
        return self._result

    @result.setter
    def result(self, result: str):
        """Sets the result of this VCardResponse.


        :param result: The result of this VCardResponse.
        :type result: str
        """

        self._result = result

    @property
    def error(self) -> str:
        """Gets the error of this VCardResponse.


        :return: The error of this VCardResponse.
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error: str):
        """Sets the error of this VCardResponse.


        :param error: The error of this VCardResponse.
        :type error: str
        """

        self._error = error
